# Generated by Django 2.0.1 on 2018-02-20 20:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('givecampus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 20, 20, 9, 46, 732429, tzinfo=utc)),
        ),
    ]
