# Generated by Django 2.0.1 on 2018-02-20 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('givecampus', '0002_auto_20180220_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
