# Generated by Django 2.0.1 on 2018-02-20 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('givecampus', '0005_auto_20180220_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='user',
            new_name='donor',
        ),
    ]
