# Generated by Django 2.0.1 on 2018-02-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givecampus', '0009_match_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
