# Generated by Django 2.0.1 on 2018-02-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givecampus', '0010_match_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
